# Generated by Django 3.1.4 on 2021-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='emp/profiles/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('nic', models.TextField(blank=True, null=True)),
                ('org_id', models.TextField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, choices=[('CEO', 'Chief Executive Officer'), ('DIR', 'Director'), ('MAN', 'Manager'), ('WOR', 'Worker'), ('OTH', 'Other')], max_length=3, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Emnployees',
            },
        ),
    ]
