# Generated by Django 3.1.6 on 2021-02-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210131_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_calls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('outbound_calls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('calls_answered', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sales_made', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.task')),
            ],
            options={
                'verbose_name_plural': 'Task Progress',
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_calls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('outbound_calls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('calls_answered', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sales_made', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.employee')),
            ],
            options={
                'verbose_name_plural': 'Daily Progress',
            },
        ),
    ]
