# Generated by Django 3.1.6 on 2021-02-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210202_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(to='application.Employee')),
            ],
            options={
                'verbose_name_plural': 'Daily Progress',
            },
        ),
        migrations.CreateModel(
            name='RegularReportStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_calls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('outbound_calls', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('calls_answered', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sales_made', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.employee')),
            ],
            options={
                'verbose_name': 'Employee Current Report',
                'verbose_name_plural': 'Employee Regular Reports',
            },
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='task',
        ),
        migrations.DeleteModel(
            name='DailyProgress',
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
