# Generated by Django 3.1.6 on 2021-02-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_regularreport_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreportstats',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.regularreport'),
        ),
    ]
