# Generated by Django 3.1.6 on 2021-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, help_text='Date of Birth - Format must be YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_on',
            field=models.DateTimeField(blank=True, help_text='Date of Joining - Format must be YYYY-MM-DD', null=True),
        ),
    ]
